<?php

namespace AppBundle\Repository;

/**
 * SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Permet de retrouver la serie active en fonction de l'heure, si plusieurs serie retrouvees, on ne retourne que la premiere
     * @param \DateTime $dateTime
     * @return mixed
     */
    public function getActiveSerie(\DateTime $dateTime)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('s')
            ->from('AppBundle:Serie', 's')
            ->where('s.heureDebut <= :dateTime')
            ->andWhere('s.heureFin > :dateTime')
            ->setParameter('dateTime', $dateTime)
        ;

        //$result = $qb->getQuery()->getSingleResult();
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
