CREATE SEQUENCE fos_user_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE TABLE fos_user (id INT NOT NULL, PRIMARY KEY(id));

ALTER TABLE fos_user ADD username VARCHAR(180) NOT NULL;
ALTER TABLE fos_user ADD username_canonical VARCHAR(180) NOT NULL;
ALTER TABLE fos_user ADD email VARCHAR(180) NOT NULL;
ALTER TABLE fos_user ADD email_canonical VARCHAR(180) NOT NULL;
ALTER TABLE fos_user ADD enabled BOOLEAN NOT NULL;
ALTER TABLE fos_user ADD salt VARCHAR(255) DEFAULT NULL;
ALTER TABLE fos_user ADD password VARCHAR(255) NOT NULL;
ALTER TABLE fos_user ADD last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL;
ALTER TABLE fos_user ADD confirmation_token VARCHAR(180) DEFAULT NULL;
ALTER TABLE fos_user ADD password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL;
ALTER TABLE fos_user ADD roles TEXT NOT NULL;
COMMENT ON COLUMN fos_user.roles IS '(DC2Type:array)';
CREATE UNIQUE INDEX UNIQ_957A647992FC23A8 ON fos_user (username_canonical);
CREATE UNIQUE INDEX UNIQ_957A6479A0D96FBF ON fos_user (email_canonical);
CREATE UNIQUE INDEX UNIQ_957A6479C05FB297 ON fos_user (confirmation_token);