app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

home:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

presentation_index:
    path:      /presentation
    defaults:  { _controller: AppBundle:Presentation:index }

presentation_add:
    path:      /presentation/add
    defaults:  { _controller: AppBundle:Presentation:add }

presentation_edit:
    path:      /presentation/{presentationId}
    defaults:  { _controller: AppBundle:Presentation:edit }

serie_index:
    path:      /serie
    defaults:  { _controller: AppBundle:Serie:index }

serie_manage:
    path:      /serie/{serieId}
    defaults:  { _controller: AppBundle:Serie:manage }

serie_test_affichage:
    path:      /display
    defaults:  { _controller: AppBundle:Display:index }

serie_active:
    path:      /display/active
    defaults:  { _controller: AppBundle:Display:getAffichage }

