app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

home:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

presentation_index:
    path:      /presentation
    defaults:  { _controller: AppBundle:Presentation:index }

presentation_add:
    path:      /presentation/add
    defaults:  { _controller: AppBundle:Presentation:add }

presentation_edit:
    path:      /presentation/{presentationId}
    defaults:  { _controller: AppBundle:Presentation:edit }

presentation_delete:
    path:      /presentation/{presentationId}/delete
    defaults:  { _controller: AppBundle:Presentation:delete }

serie_index:
    path:      /serie
    defaults:  { _controller: AppBundle:Serie:index }
    
serie_add:
    path:      /serie/add
    defaults:  { _controller: AppBundle:Serie:add }

serie_delete:
    path:      /serie/{serieId}/delete
    defaults:  { _controller: AppBundle:Serie:delete }

serie_manage:
    path:      /serie/{serieId}/manage
    defaults:  { _controller: AppBundle:Serie:manage }

serie_test_affichage:
    path:      /display
    defaults:  { _controller: AppBundle:Display:index }

serie_active:
    path:      /display/active
    defaults:  { _controller: AppBundle:Display:getAffichage }

display_previsualisation:
    path:      /display/previsualisation
    defaults:  { _controller: AppBundle:Display:previsualisation }

