app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

presentation_index:
    path:      /presentation
    defaults:  { _controller: AppBundle:Presentation:index }

presentation_add:
    path:      /presentation/add
    defaults:  { _controller: AppBundle:Presentation:add }

affichage_index:
    path:      /serie
    defaults:  { _controller: AppBundle:Serie:index }

affichage_manage:
    path:      /serie/{serieId}
    defaults:  { _controller: AppBundle:Serie:manage }

