app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

presentation_index:
    path:      /presentation
    defaults:  { _controller: AppBundle:Presentation:index }

presentation_add:
    path:      /presentation/add
    defaults:  { _controller: AppBundle:Presentation:add }

presentation_manage:
    path:      /presentation/manage
    defaults:  { _controller: AppBundle:Presentation:manage }

