AppBundle\Entity\Affichage:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AffichageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
    manyToOne:
        serie:
            targetEntity: Serie
            inversedBy: affichages
            joinColumn:
                name: serie_id
                referencedColumnName: id
        presentation:
            targetEntity: Presentation
            inversedBy: affichages
            joinColumn:
                name: presentation_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
