AppBundle\Entity\Presentation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PresentationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        url:
            type: string
            length: '512'
        active:
            type: boolean
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: presentations
            joinColumn:
                name: category_id
                referencedColumnName: id
    oneToMany:
        series:
            targetEntity: Serie
            mappedBy: presentation

    lifecycleCallbacks: {  }
