AppBundle\Entity\Presentation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PresentationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        url:
            type: string
            length: '512'
        active:
            type: boolean
            default: true
        slidesNumber:
            type: integer
            nullable: TRUE
        slideDuration:
            type: integer
            nullable: TRUE
        slideTransitionDuration:
            type: float
            nullable: TRUE
        presentationDuration:
            type: integer
            nullable: TRUE
        IdGoogleSlide:
            type: string
            length: 128
            nullable: TRUE
        sliderLoop:
            type: boolean
            default: true
        sliderAutostart:
            type: boolean
            default: true
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: presentations
            joinColumn:
                name: category_id
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: presentations
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToMany:
        affichages:
            targetEntity: Affichage
            mappedBy: presentation

    lifecycleCallbacks: {  }
