AppBundle\Entity\Serie:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SerieRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        heureDebut:
            type: time
        heureFin:
            type: time
    oneToMany:
        affichages:
            targetEntity: Affichage
            mappedBy: serie
            orphanRemoval: true
    manyToOne:
        user:
            targetEntity: User
            inversedBy: series
            joinColumn:
                name: user_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
